# Site settings
title: Thoughts From Marz
header-img: img/home-bg.png
email: mmarziano1@gmail.com
copyright_name: mmarziano
description: > # this means to ignore newlines until "baseurl:"
  Random Musings About Earth
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mmarziano
learn_profile: mmarziano
email_username: mmarziano1@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
